# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommandBO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommandBO.proto',
  package='com.purefun.fstp.core.bo',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x43ommandBO.proto\x12\x18\x63om.purefun.fstp.core.bo\"\x9e\x01\n\tCommandBO\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x62oid\x18\x02 \x01(\x12\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x15\n\rtargetService\x18\x04 \x01(\t\x12\r\n\x05parm0\x18\x05 \x01(\t\x12\r\n\x05parm1\x18\x06 \x01(\t\x12\r\n\x05parm2\x18\x07 \x01(\t\x12\r\n\x05parm3\x18\x08 \x01(\t\x12\r\n\x05parm4\x18\t \x01(\t')
)




_COMMANDBO = _descriptor.Descriptor(
  name='CommandBO',
  full_name='com.purefun.fstp.core.bo.CommandBO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='com.purefun.fstp.core.bo.CommandBO.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boid', full_name='com.purefun.fstp.core.bo.CommandBO.boid', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='com.purefun.fstp.core.bo.CommandBO.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetService', full_name='com.purefun.fstp.core.bo.CommandBO.targetService', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm0', full_name='com.purefun.fstp.core.bo.CommandBO.parm0', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm1', full_name='com.purefun.fstp.core.bo.CommandBO.parm1', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm2', full_name='com.purefun.fstp.core.bo.CommandBO.parm2', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm3', full_name='com.purefun.fstp.core.bo.CommandBO.parm3', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parm4', full_name='com.purefun.fstp.core.bo.CommandBO.parm4', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['CommandBO'] = _COMMANDBO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandBO = _reflection.GeneratedProtocolMessageType('CommandBO', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDBO,
  __module__ = 'CommandBO_pb2'
  # @@protoc_insertion_point(class_scope:com.purefun.fstp.core.bo.CommandBO)
  ))
_sym_db.RegisterMessage(CommandBO)


# @@protoc_insertion_point(module_scope)
