// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandBO.proto

package com.purefun.fstp.core.bo.pro;

public final class CommandBO_PRO {
  private CommandBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommandBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional sint64 boid = 2;</code>
     */
    boolean hasBoid();
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    long getBoid();

    /**
     * <code>optional string destination = 3;</code>
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    java.lang.String getDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <code>optional string targetService = 4;</code>
     */
    boolean hasTargetService();
    /**
     * <code>optional string targetService = 4;</code>
     */
    java.lang.String getTargetService();
    /**
     * <code>optional string targetService = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetServiceBytes();

    /**
     * <code>optional string parm0 = 5;</code>
     */
    boolean hasParm0();
    /**
     * <code>optional string parm0 = 5;</code>
     */
    java.lang.String getParm0();
    /**
     * <code>optional string parm0 = 5;</code>
     */
    com.google.protobuf.ByteString
        getParm0Bytes();

    /**
     * <code>optional string parm1 = 6;</code>
     */
    boolean hasParm1();
    /**
     * <code>optional string parm1 = 6;</code>
     */
    java.lang.String getParm1();
    /**
     * <code>optional string parm1 = 6;</code>
     */
    com.google.protobuf.ByteString
        getParm1Bytes();

    /**
     * <code>optional string parm2 = 7;</code>
     */
    boolean hasParm2();
    /**
     * <code>optional string parm2 = 7;</code>
     */
    java.lang.String getParm2();
    /**
     * <code>optional string parm2 = 7;</code>
     */
    com.google.protobuf.ByteString
        getParm2Bytes();

    /**
     * <code>optional string parm3 = 8;</code>
     */
    boolean hasParm3();
    /**
     * <code>optional string parm3 = 8;</code>
     */
    java.lang.String getParm3();
    /**
     * <code>optional string parm3 = 8;</code>
     */
    com.google.protobuf.ByteString
        getParm3Bytes();

    /**
     * <code>optional string parm4 = 9;</code>
     */
    boolean hasParm4();
    /**
     * <code>optional string parm4 = 9;</code>
     */
    java.lang.String getParm4();
    /**
     * <code>optional string parm4 = 9;</code>
     */
    com.google.protobuf.ByteString
        getParm4Bytes();
  }
  /**
   * Protobuf type {@code CommandBO}
   */
  public  static final class CommandBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommandBO)
      CommandBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandBO.newBuilder() to construct.
    private CommandBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandBO() {
      uuid_ = "";
      boid_ = 0L;
      destination_ = "";
      targetService_ = "";
      parm0_ = "";
      parm1_ = "";
      parm2_ = "";
      parm3_ = "";
      parm4_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boid_ = input.readSInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destination_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              targetService_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              parm0_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              parm1_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              parm2_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              parm3_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              parm4_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fstp.core.bo.pro.CommandBO_PRO.internal_static_CommandBO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fstp.core.bo.pro.CommandBO_PRO.internal_static_CommandBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.class, com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public boolean hasBoid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public long getBoid() {
      return boid_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <code>optional string destination = 3;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETSERVICE_FIELD_NUMBER = 4;
    private volatile java.lang.Object targetService_;
    /**
     * <code>optional string targetService = 4;</code>
     */
    public boolean hasTargetService() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string targetService = 4;</code>
     */
    public java.lang.String getTargetService() {
      java.lang.Object ref = targetService_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetService_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetService = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetServiceBytes() {
      java.lang.Object ref = targetService_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetService_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARM0_FIELD_NUMBER = 5;
    private volatile java.lang.Object parm0_;
    /**
     * <code>optional string parm0 = 5;</code>
     */
    public boolean hasParm0() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string parm0 = 5;</code>
     */
    public java.lang.String getParm0() {
      java.lang.Object ref = parm0_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parm0_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parm0 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getParm0Bytes() {
      java.lang.Object ref = parm0_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parm0_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARM1_FIELD_NUMBER = 6;
    private volatile java.lang.Object parm1_;
    /**
     * <code>optional string parm1 = 6;</code>
     */
    public boolean hasParm1() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string parm1 = 6;</code>
     */
    public java.lang.String getParm1() {
      java.lang.Object ref = parm1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parm1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parm1 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getParm1Bytes() {
      java.lang.Object ref = parm1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parm1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARM2_FIELD_NUMBER = 7;
    private volatile java.lang.Object parm2_;
    /**
     * <code>optional string parm2 = 7;</code>
     */
    public boolean hasParm2() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string parm2 = 7;</code>
     */
    public java.lang.String getParm2() {
      java.lang.Object ref = parm2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parm2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parm2 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getParm2Bytes() {
      java.lang.Object ref = parm2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parm2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARM3_FIELD_NUMBER = 8;
    private volatile java.lang.Object parm3_;
    /**
     * <code>optional string parm3 = 8;</code>
     */
    public boolean hasParm3() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string parm3 = 8;</code>
     */
    public java.lang.String getParm3() {
      java.lang.Object ref = parm3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parm3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parm3 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getParm3Bytes() {
      java.lang.Object ref = parm3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parm3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARM4_FIELD_NUMBER = 9;
    private volatile java.lang.Object parm4_;
    /**
     * <code>optional string parm4 = 9;</code>
     */
    public boolean hasParm4() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string parm4 = 9;</code>
     */
    public java.lang.String getParm4() {
      java.lang.Object ref = parm4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parm4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parm4 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getParm4Bytes() {
      java.lang.Object ref = parm4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parm4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetService_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parm0_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, parm1_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, parm2_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, parm3_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, parm4_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, targetService_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parm0_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, parm1_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, parm2_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, parm3_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, parm4_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO)) {
        return super.equals(obj);
      }
      com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO other = (com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasBoid() == other.hasBoid());
      if (hasBoid()) {
        result = result && (getBoid()
            == other.getBoid());
      }
      result = result && (hasDestination() == other.hasDestination());
      if (hasDestination()) {
        result = result && getDestination()
            .equals(other.getDestination());
      }
      result = result && (hasTargetService() == other.hasTargetService());
      if (hasTargetService()) {
        result = result && getTargetService()
            .equals(other.getTargetService());
      }
      result = result && (hasParm0() == other.hasParm0());
      if (hasParm0()) {
        result = result && getParm0()
            .equals(other.getParm0());
      }
      result = result && (hasParm1() == other.hasParm1());
      if (hasParm1()) {
        result = result && getParm1()
            .equals(other.getParm1());
      }
      result = result && (hasParm2() == other.hasParm2());
      if (hasParm2()) {
        result = result && getParm2()
            .equals(other.getParm2());
      }
      result = result && (hasParm3() == other.hasParm3());
      if (hasParm3()) {
        result = result && getParm3()
            .equals(other.getParm3());
      }
      result = result && (hasParm4() == other.hasParm4());
      if (hasParm4()) {
        result = result && getParm4()
            .equals(other.getParm4());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasBoid()) {
        hash = (37 * hash) + BOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBoid());
      }
      if (hasDestination()) {
        hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
        hash = (53 * hash) + getDestination().hashCode();
      }
      if (hasTargetService()) {
        hash = (37 * hash) + TARGETSERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getTargetService().hashCode();
      }
      if (hasParm0()) {
        hash = (37 * hash) + PARM0_FIELD_NUMBER;
        hash = (53 * hash) + getParm0().hashCode();
      }
      if (hasParm1()) {
        hash = (37 * hash) + PARM1_FIELD_NUMBER;
        hash = (53 * hash) + getParm1().hashCode();
      }
      if (hasParm2()) {
        hash = (37 * hash) + PARM2_FIELD_NUMBER;
        hash = (53 * hash) + getParm2().hashCode();
      }
      if (hasParm3()) {
        hash = (37 * hash) + PARM3_FIELD_NUMBER;
        hash = (53 * hash) + getParm3().hashCode();
      }
      if (hasParm4()) {
        hash = (37 * hash) + PARM4_FIELD_NUMBER;
        hash = (53 * hash) + getParm4().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommandBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommandBO)
        com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fstp.core.bo.pro.CommandBO_PRO.internal_static_CommandBO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fstp.core.bo.pro.CommandBO_PRO.internal_static_CommandBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.class, com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.Builder.class);
      }

      // Construct using com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        boid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        targetService_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        parm0_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        parm1_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        parm2_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        parm3_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        parm4_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fstp.core.bo.pro.CommandBO_PRO.internal_static_CommandBO_descriptor;
      }

      public com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO getDefaultInstanceForType() {
        return com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.getDefaultInstance();
      }

      public com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO build() {
        com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO buildPartial() {
        com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO result = new com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.boid_ = boid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.targetService_ = targetService_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.parm0_ = parm0_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.parm1_ = parm1_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.parm2_ = parm2_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.parm3_ = parm3_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.parm4_ = parm4_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO) {
          return mergeFrom((com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO other) {
        if (other == com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasBoid()) {
          setBoid(other.getBoid());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00000004;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasTargetService()) {
          bitField0_ |= 0x00000008;
          targetService_ = other.targetService_;
          onChanged();
        }
        if (other.hasParm0()) {
          bitField0_ |= 0x00000010;
          parm0_ = other.parm0_;
          onChanged();
        }
        if (other.hasParm1()) {
          bitField0_ |= 0x00000020;
          parm1_ = other.parm1_;
          onChanged();
        }
        if (other.hasParm2()) {
          bitField0_ |= 0x00000040;
          parm2_ = other.parm2_;
          onChanged();
        }
        if (other.hasParm3()) {
          bitField0_ |= 0x00000080;
          parm3_ = other.parm3_;
          onChanged();
        }
        if (other.hasParm4()) {
          bitField0_ |= 0x00000100;
          parm4_ = other.parm4_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public boolean hasBoid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder setBoid(long value) {
        bitField0_ |= 0x00000002;
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder clearBoid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>optional string destination = 3;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destination_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetService_ = "";
      /**
       * <code>optional string targetService = 4;</code>
       */
      public boolean hasTargetService() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string targetService = 4;</code>
       */
      public java.lang.String getTargetService() {
        java.lang.Object ref = targetService_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetService_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetService = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetServiceBytes() {
        java.lang.Object ref = targetService_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetService_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetService = 4;</code>
       */
      public Builder setTargetService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetService_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetService = 4;</code>
       */
      public Builder clearTargetService() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetService_ = getDefaultInstance().getTargetService();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetService = 4;</code>
       */
      public Builder setTargetServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetService_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parm0_ = "";
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public boolean hasParm0() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public java.lang.String getParm0() {
        java.lang.Object ref = parm0_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parm0_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getParm0Bytes() {
        java.lang.Object ref = parm0_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parm0_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public Builder setParm0(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        parm0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public Builder clearParm0() {
        bitField0_ = (bitField0_ & ~0x00000010);
        parm0_ = getDefaultInstance().getParm0();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm0 = 5;</code>
       */
      public Builder setParm0Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        parm0_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parm1_ = "";
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public boolean hasParm1() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public java.lang.String getParm1() {
        java.lang.Object ref = parm1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parm1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getParm1Bytes() {
        java.lang.Object ref = parm1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parm1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public Builder setParm1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        parm1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public Builder clearParm1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        parm1_ = getDefaultInstance().getParm1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm1 = 6;</code>
       */
      public Builder setParm1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        parm1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parm2_ = "";
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public boolean hasParm2() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public java.lang.String getParm2() {
        java.lang.Object ref = parm2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parm2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getParm2Bytes() {
        java.lang.Object ref = parm2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parm2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public Builder setParm2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        parm2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public Builder clearParm2() {
        bitField0_ = (bitField0_ & ~0x00000040);
        parm2_ = getDefaultInstance().getParm2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm2 = 7;</code>
       */
      public Builder setParm2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        parm2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parm3_ = "";
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public boolean hasParm3() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public java.lang.String getParm3() {
        java.lang.Object ref = parm3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parm3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getParm3Bytes() {
        java.lang.Object ref = parm3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parm3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public Builder setParm3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        parm3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public Builder clearParm3() {
        bitField0_ = (bitField0_ & ~0x00000080);
        parm3_ = getDefaultInstance().getParm3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm3 = 8;</code>
       */
      public Builder setParm3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        parm3_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parm4_ = "";
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public boolean hasParm4() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public java.lang.String getParm4() {
        java.lang.Object ref = parm4_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parm4_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public com.google.protobuf.ByteString
          getParm4Bytes() {
        java.lang.Object ref = parm4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parm4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public Builder setParm4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        parm4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public Builder clearParm4() {
        bitField0_ = (bitField0_ & ~0x00000100);
        parm4_ = getDefaultInstance().getParm4();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parm4 = 9;</code>
       */
      public Builder setParm4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        parm4_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommandBO)
    }

    // @@protoc_insertion_point(class_scope:CommandBO)
    private static final com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO();
    }

    public static com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommandBO>
        PARSER = new com.google.protobuf.AbstractParser<CommandBO>() {
      public CommandBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandBO> getParserForType() {
      return PARSER;
    }

    public com.purefun.fstp.core.bo.pro.CommandBO_PRO.CommandBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CommandBO.proto\032\031google/protobuf/any.p" +
      "roto\"\236\001\n\tCommandBO\022\014\n\004uuid\030\001 \001(\t\022\014\n\004boid" +
      "\030\002 \001(\022\022\023\n\013destination\030\003 \001(\t\022\025\n\rtargetSer" +
      "vice\030\004 \001(\t\022\r\n\005parm0\030\005 \001(\t\022\r\n\005parm1\030\006 \001(\t" +
      "\022\r\n\005parm2\030\007 \001(\t\022\r\n\005parm3\030\010 \001(\t\022\r\n\005parm4\030" +
      "\t \001(\tB-\n\034com.purefun.fstp.core.bo.proB\rC" +
      "ommandBO_PRO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_CommandBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommandBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Destination", "TargetService", "Parm0", "Parm1", "Parm2", "Parm3", "Parm4", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
