// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MarketBarBO.proto

package com.purefun.fstp.core.bo.pro;

public final class MarketBarBO_PRO {
  private MarketBarBO_PRO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MarketBarBOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MarketBarBO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional sint64 boid = 2;</code>
     */
    boolean hasBoid();
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    long getBoid();

    /**
     * <code>optional string destination = 3;</code>
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    java.lang.String getDestination();
    /**
     * <code>optional string destination = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <code>optional string product_id = 4;</code>
     */
    boolean hasProductId();
    /**
     * <code>optional string product_id = 4;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>optional string product_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>optional string exch = 5;</code>
     */
    boolean hasExch();
    /**
     * <code>optional string exch = 5;</code>
     */
    java.lang.String getExch();
    /**
     * <code>optional string exch = 5;</code>
     */
    com.google.protobuf.ByteString
        getExchBytes();

    /**
     * <code>optional string date = 6;</code>
     */
    boolean hasDate();
    /**
     * <code>optional string date = 6;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string date = 6;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>optional double high = 7;</code>
     */
    boolean hasHigh();
    /**
     * <code>optional double high = 7;</code>
     */
    double getHigh();

    /**
     * <code>optional double low = 8;</code>
     */
    boolean hasLow();
    /**
     * <code>optional double low = 8;</code>
     */
    double getLow();

    /**
     * <code>optional double open = 9;</code>
     */
    boolean hasOpen();
    /**
     * <code>optional double open = 9;</code>
     */
    double getOpen();

    /**
     * <code>optional double close = 10;</code>
     */
    boolean hasClose();
    /**
     * <code>optional double close = 10;</code>
     */
    double getClose();

    /**
     * <code>optional double change = 11;</code>
     */
    boolean hasChange();
    /**
     * <code>optional double change = 11;</code>
     */
    double getChange();

    /**
     * <code>optional double volume = 12;</code>
     */
    boolean hasVolume();
    /**
     * <code>optional double volume = 12;</code>
     */
    double getVolume();
  }
  /**
   * Protobuf type {@code MarketBarBO}
   */
  public  static final class MarketBarBO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MarketBarBO)
      MarketBarBOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MarketBarBO.newBuilder() to construct.
    private MarketBarBO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MarketBarBO() {
      uuid_ = "";
      boid_ = 0L;
      destination_ = "";
      productId_ = "";
      exch_ = "";
      date_ = "";
      high_ = 0D;
      low_ = 0D;
      open_ = 0D;
      close_ = 0D;
      change_ = 0D;
      volume_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MarketBarBO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boid_ = input.readSInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              destination_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              productId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              exch_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              date_ = bs;
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              high_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              low_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              open_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              close_ = input.readDouble();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              change_ = input.readDouble();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000800;
              volume_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.internal_static_MarketBarBO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.internal_static_MarketBarBO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.class, com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOID_FIELD_NUMBER = 2;
    private long boid_;
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public boolean hasBoid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint64 boid = 2;</code>
     */
    public long getBoid() {
      return boid_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object destination_;
    /**
     * <code>optional string destination = 3;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object productId_;
    /**
     * <code>optional string product_id = 4;</code>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string product_id = 4;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string product_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCH_FIELD_NUMBER = 5;
    private volatile java.lang.Object exch_;
    /**
     * <code>optional string exch = 5;</code>
     */
    public boolean hasExch() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string exch = 5;</code>
     */
    public java.lang.String getExch() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exch_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exch = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExchBytes() {
      java.lang.Object ref = exch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object date_;
    /**
     * <code>optional string date = 6;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string date = 6;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HIGH_FIELD_NUMBER = 7;
    private double high_;
    /**
     * <code>optional double high = 7;</code>
     */
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double high = 7;</code>
     */
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 8;
    private double low_;
    /**
     * <code>optional double low = 8;</code>
     */
    public boolean hasLow() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double low = 8;</code>
     */
    public double getLow() {
      return low_;
    }

    public static final int OPEN_FIELD_NUMBER = 9;
    private double open_;
    /**
     * <code>optional double open = 9;</code>
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double open = 9;</code>
     */
    public double getOpen() {
      return open_;
    }

    public static final int CLOSE_FIELD_NUMBER = 10;
    private double close_;
    /**
     * <code>optional double close = 10;</code>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional double close = 10;</code>
     */
    public double getClose() {
      return close_;
    }

    public static final int CHANGE_FIELD_NUMBER = 11;
    private double change_;
    /**
     * <code>optional double change = 11;</code>
     */
    public boolean hasChange() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional double change = 11;</code>
     */
    public double getChange() {
      return change_;
    }

    public static final int VOLUME_FIELD_NUMBER = 12;
    private double volume_;
    /**
     * <code>optional double volume = 12;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional double volume = 12;</code>
     */
    public double getVolume() {
      return volume_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, date_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, high_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, low_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, open_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, close_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeDouble(11, change_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeDouble(12, volume_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, boid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destination_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, date_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, high_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, low_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, open_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, close_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, change_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, volume_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO)) {
        return super.equals(obj);
      }
      com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO other = (com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasBoid() == other.hasBoid());
      if (hasBoid()) {
        result = result && (getBoid()
            == other.getBoid());
      }
      result = result && (hasDestination() == other.hasDestination());
      if (hasDestination()) {
        result = result && getDestination()
            .equals(other.getDestination());
      }
      result = result && (hasProductId() == other.hasProductId());
      if (hasProductId()) {
        result = result && getProductId()
            .equals(other.getProductId());
      }
      result = result && (hasExch() == other.hasExch());
      if (hasExch()) {
        result = result && getExch()
            .equals(other.getExch());
      }
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && (hasHigh() == other.hasHigh());
      if (hasHigh()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getHigh())
            == java.lang.Double.doubleToLongBits(
                other.getHigh()));
      }
      result = result && (hasLow() == other.hasLow());
      if (hasLow()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLow())
            == java.lang.Double.doubleToLongBits(
                other.getLow()));
      }
      result = result && (hasOpen() == other.hasOpen());
      if (hasOpen()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getOpen())
            == java.lang.Double.doubleToLongBits(
                other.getOpen()));
      }
      result = result && (hasClose() == other.hasClose());
      if (hasClose()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getClose())
            == java.lang.Double.doubleToLongBits(
                other.getClose()));
      }
      result = result && (hasChange() == other.hasChange());
      if (hasChange()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getChange())
            == java.lang.Double.doubleToLongBits(
                other.getChange()));
      }
      result = result && (hasVolume() == other.hasVolume());
      if (hasVolume()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getVolume())
            == java.lang.Double.doubleToLongBits(
                other.getVolume()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasBoid()) {
        hash = (37 * hash) + BOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBoid());
      }
      if (hasDestination()) {
        hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
        hash = (53 * hash) + getDestination().hashCode();
      }
      if (hasProductId()) {
        hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getProductId().hashCode();
      }
      if (hasExch()) {
        hash = (37 * hash) + EXCH_FIELD_NUMBER;
        hash = (53 * hash) + getExch().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasHigh()) {
        hash = (37 * hash) + HIGH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getHigh()));
      }
      if (hasLow()) {
        hash = (37 * hash) + LOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLow()));
      }
      if (hasOpen()) {
        hash = (37 * hash) + OPEN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getOpen()));
      }
      if (hasClose()) {
        hash = (37 * hash) + CLOSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getClose()));
      }
      if (hasChange()) {
        hash = (37 * hash) + CHANGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getChange()));
      }
      if (hasVolume()) {
        hash = (37 * hash) + VOLUME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getVolume()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MarketBarBO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MarketBarBO)
        com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.internal_static_MarketBarBO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.internal_static_MarketBarBO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.class, com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.Builder.class);
      }

      // Construct using com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        boid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        productId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        exch_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        high_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        low_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        open_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        close_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        change_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        volume_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.internal_static_MarketBarBO_descriptor;
      }

      public com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO getDefaultInstanceForType() {
        return com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.getDefaultInstance();
      }

      public com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO build() {
        com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO buildPartial() {
        com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO result = new com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.boid_ = boid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exch_ = exch_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.close_ = close_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.change_ = change_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.volume_ = volume_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO) {
          return mergeFrom((com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO other) {
        if (other == com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasBoid()) {
          setBoid(other.getBoid());
        }
        if (other.hasDestination()) {
          bitField0_ |= 0x00000004;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasProductId()) {
          bitField0_ |= 0x00000008;
          productId_ = other.productId_;
          onChanged();
        }
        if (other.hasExch()) {
          bitField0_ |= 0x00000010;
          exch_ = other.exch_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000020;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasClose()) {
          setClose(other.getClose());
        }
        if (other.hasChange()) {
          setChange(other.getChange());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private long boid_ ;
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public boolean hasBoid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public long getBoid() {
        return boid_;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder setBoid(long value) {
        bitField0_ |= 0x00000002;
        boid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 boid = 2;</code>
       */
      public Builder clearBoid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object destination_ = "";
      /**
       * <code>optional string destination = 3;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destination_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 3;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        destination_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>optional string product_id = 4;</code>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string product_id = 4;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product_id = 4;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_id = 4;</code>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_id = 4;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        productId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exch_ = "";
      /**
       * <code>optional string exch = 5;</code>
       */
      public boolean hasExch() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string exch = 5;</code>
       */
      public java.lang.String getExch() {
        java.lang.Object ref = exch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exch_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exch = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExchBytes() {
        java.lang.Object ref = exch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exch = 5;</code>
       */
      public Builder setExch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exch = 5;</code>
       */
      public Builder clearExch() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exch_ = getDefaultInstance().getExch();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exch = 5;</code>
       */
      public Builder setExchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>optional string date = 6;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 6;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        date_ = value;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>optional double high = 7;</code>
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double high = 7;</code>
       */
      public double getHigh() {
        return high_;
      }
      /**
       * <code>optional double high = 7;</code>
       */
      public Builder setHigh(double value) {
        bitField0_ |= 0x00000040;
        high_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double high = 7;</code>
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000040);
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>optional double low = 8;</code>
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double low = 8;</code>
       */
      public double getLow() {
        return low_;
      }
      /**
       * <code>optional double low = 8;</code>
       */
      public Builder setLow(double value) {
        bitField0_ |= 0x00000080;
        low_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double low = 8;</code>
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000080);
        low_ = 0D;
        onChanged();
        return this;
      }

      private double open_ ;
      /**
       * <code>optional double open = 9;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double open = 9;</code>
       */
      public double getOpen() {
        return open_;
      }
      /**
       * <code>optional double open = 9;</code>
       */
      public Builder setOpen(double value) {
        bitField0_ |= 0x00000100;
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double open = 9;</code>
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000100);
        open_ = 0D;
        onChanged();
        return this;
      }

      private double close_ ;
      /**
       * <code>optional double close = 10;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional double close = 10;</code>
       */
      public double getClose() {
        return close_;
      }
      /**
       * <code>optional double close = 10;</code>
       */
      public Builder setClose(double value) {
        bitField0_ |= 0x00000200;
        close_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double close = 10;</code>
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000200);
        close_ = 0D;
        onChanged();
        return this;
      }

      private double change_ ;
      /**
       * <code>optional double change = 11;</code>
       */
      public boolean hasChange() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double change = 11;</code>
       */
      public double getChange() {
        return change_;
      }
      /**
       * <code>optional double change = 11;</code>
       */
      public Builder setChange(double value) {
        bitField0_ |= 0x00000400;
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double change = 11;</code>
       */
      public Builder clearChange() {
        bitField0_ = (bitField0_ & ~0x00000400);
        change_ = 0D;
        onChanged();
        return this;
      }

      private double volume_ ;
      /**
       * <code>optional double volume = 12;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional double volume = 12;</code>
       */
      public double getVolume() {
        return volume_;
      }
      /**
       * <code>optional double volume = 12;</code>
       */
      public Builder setVolume(double value) {
        bitField0_ |= 0x00000800;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double volume = 12;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000800);
        volume_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MarketBarBO)
    }

    // @@protoc_insertion_point(class_scope:MarketBarBO)
    private static final com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO();
    }

    public static com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MarketBarBO>
        PARSER = new com.google.protobuf.AbstractParser<MarketBarBO>() {
      public MarketBarBO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarketBarBO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MarketBarBO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MarketBarBO> getParserForType() {
      return PARSER;
    }

    public com.purefun.fstp.core.bo.pro.MarketBarBO_PRO.MarketBarBO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarketBarBO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketBarBO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MarketBarBO.proto\032\031google/protobuf/any" +
      ".proto\"\306\001\n\013MarketBarBO\022\014\n\004uuid\030\001 \001(\t\022\014\n\004" +
      "boid\030\002 \001(\022\022\023\n\013destination\030\003 \001(\t\022\022\n\nprodu" +
      "ct_id\030\004 \001(\t\022\014\n\004exch\030\005 \001(\t\022\014\n\004date\030\006 \001(\t\022" +
      "\014\n\004high\030\007 \001(\001\022\013\n\003low\030\010 \001(\001\022\014\n\004open\030\t \001(\001" +
      "\022\r\n\005close\030\n \001(\001\022\016\n\006change\030\013 \001(\001\022\016\n\006volum" +
      "e\030\014 \001(\001B/\n\034com.purefun.fstp.core.bo.proB" +
      "\017MarketBarBO_PRO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_MarketBarBO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MarketBarBO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketBarBO_descriptor,
        new java.lang.String[] { "Uuid", "Boid", "Destination", "ProductId", "Exch", "Date", "High", "Low", "Open", "Close", "Change", "Volume", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
