logging:
    file= src/main/resource/log4j2.xml 
    
server:
    port: 8888

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-second: 60
      
spring:
    application:
        name: ${ServiceName}_${Env}_${Instance} 
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        consumer:
            group-id: test
            enable-auto-commit: true
            auto-commit-interval: 1000
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer  



            